# Generated by Django 6.0.4 on 2026-05-18 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0009_alter_student_options_student_is_graduated_and_more'),
        ('teachers', '0005_employee_assigned_class_employee_assigned_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviourRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('behaviour_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Neutral', 'Neutral')], default='Positive', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_behaviour_records', to='teachers.employee')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('discipline', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('punctuality', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('cleanliness', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('communication', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('teamwork', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('leadership', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('homework_habit', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('class_participation', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Average', 'Average'), ('Needs Improvement', 'Needs Improvement')], default='Good', max_length=30)),
                ('teacher_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evaluations', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_skill_evaluations', to='teachers.employee')),
            ],
            options={
                'ordering': ['-year', '-id'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
