# Generated by Django 6.0.4 on 2026-05-01 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession'),
        ('students', '0002_student_sibling_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
    ]
