# Generated by Django 6.0.4 on 2026-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_current_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
