# Generated by Django 6.0.4 on 2026-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parent',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='login_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
