# Generated by Django 6.0.4 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_parent_password_alter_parent_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
