# Generated by Django 6.0.4 on 2026-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_options_student_is_graduated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hindu', 'Hindu'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Buddhist', 'Buddhist'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
