# Generated by Django 6.0.4 on 2026-05-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_religion_student_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_login', to='students.student'),
        ),
    ]
