# Generated by Django 6.0.4 on 2026-06-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_deleted_at_student_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_deleted',
        ),
    ]
