# Generated by Django 6.0.4 on 2026-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contactmessage_admission_aadhaar_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='student_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='registration_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
