# Generated by Django 6.0.4 on 2026-05-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_gallery_infrastructure_schoolevent_whychoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_type', models.CharField(choices=[('Result', 'Result'), ('Routine', 'Routine'), ('Notice', 'Notice'), ('Syllabus', 'Syllabus'), ('Form', 'Form'), ('Other', 'Other')], default='Other', max_length=50)),
                ('pdf_file', models.FileField(upload_to='website_downloads/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='website_gallery_videos/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website_gallery/'),
        ),
    ]
