# Generated by Django 6.0.4 on 2026-05-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_downloadfile_gallery_video_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadfile',
            name='file_type',
            field=models.CharField(choices=[('Result', 'Result'), ('Routine', 'Routine'), ('Notice', 'Notice'), ('Syllabus', 'Syllabus'), ('Form', 'Admission Form'), ('Fee', 'Fee Structure'), ('Holiday', 'Holiday List'), ('Book', 'Book List'), ('Prospectus', 'Prospectus'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
