# Generated by Django 6.0.4 on 2026-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_downloadfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('student_class', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('guardian_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('session', models.CharField(default='2025-26', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
