# Generated by Django 6.0.4 on 2026-06-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='AL RAHMAN MISSION', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/favicon/')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('website_url', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('about_school', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('principal_message', models.TextField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
