# Generated by Django 6.0.4 on 2026-04-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_month', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('art_material', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('books_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Card', 'Card'), ('Bank', 'Bank')], default='Cash', max_length=20)),
                ('operator_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_collections', to='students.student')),
            ],
        ),
    ]
