# Generated by Django 6.0.4 on 2026-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Due', 'Due')], default='Due', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='feecollection',
            unique_together={('student', 'fees_month')},
        ),
    ]
