# Generated by Django 6.0.4 on 2026-05-01 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession'),
        ('fees', '0003_feecollection_receipt_no_feecollection_status_and_more'),
        ('students', '0003_student_current_session'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feecollection',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_collections', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='feecollection',
            unique_together={('student', 'session', 'fees_month')},
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_assigned', 'session')},
        ),
    ]
