# Generated by Django 6.0.4 on 2026-05-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_section_options_section_is_active'),
        ('fees', '0004_alter_feecollection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('class_assigned', 'section', 'session')},
        ),
    ]
