# Generated by Django 6.0.4 on 2026-05-31 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_classsubject_options_classsubject_subject_rank'),
        ('fees', '0005_alter_feestructure_unique_together_and_more'),
        ('students', '0011_alter_parent_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promise_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promise_date', models.DateField()),
                ('followup_type', models.CharField(choices=[('CALL', 'Call'), ('HOME_VISIT', 'Home Visit'), ('SCHOOL_MEET', 'School Meeting'), ('WHATSAPP', 'WhatsApp')], default='CALL', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALLED', 'Called'), ('VISITED', 'Visited'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('next_action', models.CharField(blank=True, help_text='Example: Call father, Visit home, Send WhatsApp reminder', max_length=200, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('result_note', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fee_followups', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_followups', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_followups', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Follow-up / Promise',
                'verbose_name_plural': 'Fee Follow-ups / Promises',
                'ordering': ['promise_date', '-priority', '-id'],
            },
        ),
    ]
