# Generated by Django 6.0.4 on 2026-06-10 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_feefollowup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fee_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feecollection',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
