# Generated by Django 6.0.4 on 2026-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admission_delete_onlineadmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
