# Generated by Django 6.0.4 on 2026-06-04 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admission_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='admission',
            name='admission_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='is_duplicate_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='previous_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status'], name='admissions__status_94726f_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['student_name'], name='admissions__student_bb530e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['mobile'], name='admissions__mobile_41d57c_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['student_class'], name='admissions__student_870e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['created_at'], name='admissions__created_0ae0d8_idx'),
        ),
    ]
