# Generated by Django 6.0.4 on 2026-05-15 06:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0008_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('TC', 'Transfer Certificate'), ('CHARACTER', 'Character Certificate'), ('BONAFIDE', 'Bonafide Certificate'), ('STUDY', 'Study Certificate'), ('FEE_CLEARANCE', 'Fee Clearance Certificate'), ('CUSTOM', 'Custom Certificate')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('session', models.CharField(blank=True, max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('conduct', models.CharField(default='Good', max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('custom_body', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qr/')),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
