# Generated by Django 6.0.4 on 2026-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
        ('students', '0009_alter_student_options_student_is_graduated_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_no'], name='certificate_certifi_e686f4_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['session'], name='certificate_session_4e4a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_type'], name='certificate_certifi_0e5b95_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issue_date'], name='certificate_issue_d_e50978_idx'),
        ),
    ]
