# Generated by Django 6.0.4 on 2026-04-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('students', '0002_student_sibling_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('max_total_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('result_status', models.CharField(default='Pass', max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
