# Generated by Django 6.0.4 on 2026-05-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_studentresultsummary'),
        ('students', '0007_alter_parent_password_alter_parent_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'ordering': ['student__id', 'subject']},
        ),
        migrations.AlterModelOptions(
            name='examroutine',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AlterModelOptions(
            name='studentresultsummary',
            options={'ordering': ['rank', '-percentage']},
        ),
        migrations.AddField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='max_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='oral_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='written_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examroutine',
            name='total_marks',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='max_total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentresultsummary',
            name='total_marks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
