# Generated by Django 6.0.4 on 2026-05-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_options_alter_examresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('written_marks', models.PositiveIntegerField(default=80)),
                ('oral_marks', models.PositiveIntegerField(default=20)),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assigns', to='exams.exam')),
            ],
            options={
                'ordering': ['exam', 'school_class', 'section', 'subject'],
                'unique_together': {('exam', 'school_class', 'section', 'subject')},
            },
        ),
    ]
