# Generated by Django 6.0.4 on 2026-05-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsubjectassign'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
