# Generated by Django 6.0.4 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examresult_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='examroutine',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
