# Generated by Django 6.0.4 on 2026-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examroutine_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubjectassign',
            name='section',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
