# Generated by Django 6.0.4 on 2026-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_examsubjectassign_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='academic_session',
            field=models.CharField(default='2025-26', max_length=20),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='academic_session',
            field=models.CharField(default='2025-26', max_length=20),
        ),
        migrations.AddField(
            model_name='examsubjectassign',
            name='academic_session',
            field=models.CharField(default='2025-26', max_length=20),
        ),
        migrations.AddField(
            model_name='studentresultsummary',
            name='academic_session',
            field=models.CharField(default='2025-26', max_length=20),
        ),
    ]
