# Generated by Django 6.0.4 on 2026-05-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_classtest_classtestresult'),
        ('students', '0009_alter_student_options_student_is_graduated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='classtestresult',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='classtest',
            name='subject',
            field=models.CharField(default='All Subjects', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='classtestresult',
            unique_together={('class_test', 'student')},
        ),
        migrations.CreateModel(
            name='ClassTestSubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('total_marks', models.FloatField(default=100)),
                ('percentage', models.FloatField(default=0)),
                ('performance', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='exams.classtest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_test_subject_marks', to='students.student')),
            ],
            options={
                'ordering': ['student__id', 'subject'],
                'unique_together': {('class_test', 'student', 'subject')},
            },
        ),
    ]
