# Generated by Django 6.0.4 on 2026-05-27 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0010_alter_classtest_options_and_more"),
        ("students", "0010_student_religion_student_village"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classtest",
            options={"ordering": ["-exam_date", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="classtestresult",
            options={"ordering": ["student__roll_no", "student__student_name"]},
        ),
        migrations.AlterModelOptions(
            name="classtestsubjectmark",
            options={"ordering": ["subject"]},
        ),
        migrations.AlterModelOptions(
            name="examresult",
            options={"ordering": ["student__roll_no", "student__student_name", "subject"]},
        ),
        migrations.AlterModelOptions(
            name="examsubjectassign",
            options={"ordering": ["school_class", "section", "subject"]},
        ),
        migrations.AlterModelOptions(
            name="studentresultsummary",
            options={"ordering": ["rank", "-percentage", "-total_marks"]},
        ),

        migrations.AlterUniqueTogether(
            name="classtestresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="studentresultsummary",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="classtestsubjectmark",
            unique_together=set(),
        ),

        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="class_test",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="performance",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="student",
        ),
        migrations.RemoveField(
            model_name="classtestsubjectmark",
            name="total_marks",
        ),
        migrations.RemoveField(
            model_name="examsubjectassign",
            name="oral_marks",
        ),
        migrations.RemoveField(
            model_name="examsubjectassign",
            name="written_marks",
        ),

        migrations.RenameField(
            model_name="classtestresult",
            old_name="obtained_marks",
            new_name="marks_obtained",
        ),
        migrations.RenameField(
            model_name="examsubjectassign",
            old_name="total_marks",
            new_name="full_marks",
        ),

        migrations.AddField(
            model_name="classtest",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="classtest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="classtestresult",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="classtestsubjectmark",
            name="class_test_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_marks",
                to="exams.classtestresult",
            ),
        ),
        migrations.AddField(
            model_name="classtestsubjectmark",
            name="max_marks",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="classtestsubjectmark",
            name="oral_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="classtestsubjectmark",
            name="written_marks",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="examroutine",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examsubjectassign",
            name="pass_marks",
            field=models.PositiveIntegerField(default=34),
        ),
        migrations.AddField(
            model_name="studentresultsummary",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AlterField(
            model_name="classtest",
            name="class_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="exam_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="section",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="subject",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="test_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="classtest",
            name="total_marks",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="classtestresult",
            name="class_test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="exams.classtest",
            ),
        ),
        migrations.AlterField(
            model_name="classtestresult",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="classtestresult",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_test_results",
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="classtestsubjectmark",
            name="subject",
            field=models.CharField(max_length=150),
        ),

        migrations.AlterField(
            model_name="exam",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="remarks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="section",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examresult",
            name="subject",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="examroutine",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examroutine",
            name="school_class",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="examroutine",
            name="section",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examroutine",
            name="subject",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="examsubjectassign",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examsubjectassign",
            name="school_class",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="examsubjectassign",
            name="section",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="examsubjectassign",
            name="subject",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="studentresultsummary",
            name="academic_session",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="studentresultsummary",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_summaries",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="studentresultsummary",
            name="grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="studentresultsummary",
            name="rank",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentresultsummary",
            name="result_status",
            field=models.CharField(default="Fail", max_length=20),
        ),

        migrations.AlterUniqueTogether(
            name="classtestresult",
            unique_together={("class_test", "student", "academic_session")},
        ),
        migrations.AlterUniqueTogether(
            name="classtestsubjectmark",
            unique_together={("class_test_result", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="examsubjectassign",
            unique_together={("exam", "academic_session", "school_class", "section", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="examresult",
            unique_together={("student", "exam", "academic_session", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="examroutine",
            unique_together={("exam", "academic_session", "school_class", "section", "subject", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="studentresultsummary",
            unique_together={("student", "exam", "academic_session")},
        ),
    ]