# Generated by Django 6.0.4 on 2026-04-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('subject_specialization', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=30, null=True)),
                ('joining_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
