# Generated by Django 6.0.4 on 2026-05-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_access_attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_exams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_payroll',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_erp_admin',
            field=models.BooleanField(default=False),
        ),
    ]
