# Generated by Django 6.0.4 on 2026-05-05 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_employee_can_access_attendance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_access_academics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_admissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_communications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_expenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_idcards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_settings',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_access_teachers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
