# Generated by Django 6.0.4 on 2026-05-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_section_options_section_is_active'),
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='academics.class'),
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
