# Generated by Django 6.0.4 on 2026-06-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_employee_assigned_class_employee_assigned_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
    ]
