# Generated by Django 6.0.4 on 2026-05-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notice_type', models.CharField(choices=[('General', 'General'), ('Urgent', 'Urgent'), ('Exam', 'Exam'), ('Holiday', 'Holiday'), ('Homework', 'Homework')], default='General', max_length=30)),
                ('target', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Teachers', 'Teachers'), ('Parents', 'Parents'), ('Class Wise', 'Class Wise')], default='All', max_length=30)),
                ('school_class', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.employee')),
            ],
        ),
    ]
