# Generated by Django 6.0.4 on 2026-04-30 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salary_advance_amount_salary_due_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='previous_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
