# Generated by Django 6.0.4 on 2026-05-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_salary_payable_amount_salary_previous_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-year', '-id']},
        ),
    ]
