# Generated by Django 6.0.4 on 2026-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_alter_salary_options'),
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salary',
            name='academic_session',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together={('employee', 'academic_session', 'month', 'year')},
        ),
    ]
