# Generated by Django 6.0.4 on 2026-05-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='handled_by_teacher',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='teacher_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='teacher_status',
            field=models.CharField(choices=[('New', 'New'), ('Submitted', 'Submitted to Admin')], default='New', max_length=30),
        ),
        migrations.AddField(
            model_name='complaint',
            name='teacher_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
