# Generated by Django 6.0.4 on 2026-05-17 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_handled_by_teacher_and_more'),
        ('students', '0009_alter_student_options_student_is_graduated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='solution',
            new_name='admin_solution',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='teacher_status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING_TEACHER', 'Pending Teacher Action'), ('PENDING_ADMIN_APPROVAL', 'Pending Admin Approval'), ('SOLVED', 'Solved'), ('REJECTED', 'Rejected / Send Back')], default='PENDING_TEACHER', max_length=40),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student'),
        ),
    ]
