# Generated by Django 6.0.4 on 2026-05-31 03:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Example: bi bi-lamp', max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=150, null=True)),
                ('room_type', models.CharField(choices=[('CLASS_ROOM', 'Class Room'), ('OFFICE', 'Office'), ('STAFF_ROOM', 'Staff Room'), ('HOSTEL_ROOM', 'Hostel Room'), ('TOILET', 'Toilet'), ('STORE_ROOM', 'Store Room'), ('LAB', 'Lab'), ('LIBRARY', 'Library'), ('OTHER', 'Other')], default='CLASS_ROOM', max_length=30)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_no'],
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('item_code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('AVERAGE', 'Average'), ('REPAIR_NEEDED', 'Repair Needed'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='GOOD', max_length=30)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('UNDER_REPAIR', 'Under Repair'), ('DISPOSED', 'Disposed')], default='IN_USE', max_length=30)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_checked_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='school_assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assets', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='school_assets.assetroom')),
            ],
            options={
                'verbose_name': 'Asset Item',
                'verbose_name_plural': 'Asset Items',
                'ordering': ['room__room_no', 'category__name', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('issue_description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('reported_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor_or_mechanic', models.CharField(blank=True, max_length=150, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='school_assets.assetitem')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_maintenance_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Maintenance',
                'verbose_name_plural': 'Asset Maintenance',
                'ordering': ['-reported_date', '-id'],
            },
        ),
    ]
