# Generated by Django 6.0.4 on 2026-05-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaintenance',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REPAIR', 'Under Repair'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
