# Generated by Django 6.0.4 on 2026-05-31 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0009_alter_classsubject_options_classsubject_subject_rank'),
        ('students', '0011_alter_parent_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='question_answers/questions/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ANSWERED', 'Answered'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='question_answers/answers/')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_visible_to_parent', models.BooleanField(default=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
                ('class_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_questions', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Question',
                'verbose_name_plural': 'Student Questions',
                'ordering': ['-asked_at'],
            },
        ),
    ]
