# Generated by Django 6.0.4 on 2026-05-05 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicsession'),
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='teachers.employee'),
        ),
    ]
