# Generated by Django 6.0.4 on 2026-05-06 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_class_class_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_marks', models.PositiveIntegerField(default=100)),
                ('pass_marks', models.PositiveIntegerField(default=35)),
                ('written_marks', models.PositiveIntegerField(default=80)),
                ('oral_marks', models.PositiveIntegerField(default=20)),
                ('practical_marks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='academics.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_classes', to='academics.subject')),
            ],
            options={
                'ordering': ['school_class__class_name', 'subject__subject_name'],
                'unique_together': {('school_class', 'subject')},
            },
        ),
    ]
