# Generated by Django 6.0.4 on 2026-05-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_section_options_section_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_date'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['class_name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='classroutine',
            options={'ordering': ['class_name', 'section', 'day', 'start_time'], 'verbose_name': 'Class Routine', 'verbose_name_plural': 'Class Routines'},
        ),
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['school_class__class_name', 'subject__subject_name'], 'verbose_name': 'Class Subject', 'verbose_name_plural': 'Class Subjects'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['school_class__class_name', 'section_name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='class',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
