# Generated by Django 6.0.4 on 2026-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_academicsession_options_alter_class_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['school_class__class_name', 'subject_rank', 'subject__subject_name'], 'verbose_name': 'Class Subject', 'verbose_name_plural': 'Class Subjects'},
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject_rank',
            field=models.PositiveIntegerField(default=0, verbose_name='Subject Rank'),
        ),
    ]
