# Generated by Django 6.0.4 on 2026-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='AL RAHMAN MISSION', max_length=200)),
                ('principal_name', models.CharField(blank=True, max_length=150, null=True)),
                ('principal_signature', models.ImageField(blank=True, null=True, upload_to='principal_sign/')),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logo/')),
                ('school_header', models.ImageField(blank=True, null=True, upload_to='school_header/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
