# Generated by Django 6.0.4 on 2026-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='count_holiday_attendance',
            field=models.BooleanField(default=False, help_text='If enabled, holiday will be counted in attendance reports'),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='half_day',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Friday', help_text='Half-day school day', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='half_day_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsetting',
            name='weekly_holiday',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Monday', help_text='Main weekly holiday for school', max_length=20),
        ),
    ]
