# Generated by Django 6.0.4 on 2026-04-20 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='distance_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_attendance_selfies/'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='within_range',
            field=models.BooleanField(default=False),
        ),
    ]
