# Generated by Django 6.0.4 on 2026-04-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_teacherattendance_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
