# Generated by Django 6.0.4 on 2026-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancealert'),
        ('students', '0007_alter_parent_password_alter_parent_username_and_more'),
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancealert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'student']},
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', '-marked_at']},
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('employee', 'date')},
        ),
    ]
