# Generated by Django 6.0.4 on 2026-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancealert_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('Weekly', 'Weekly Holiday'), ('Special', 'Special Holiday'), ('Emergency', 'Emergency Holiday'), ('Festival', 'Festival Holiday'), ('Government', 'Government Holiday')], default='Special', max_length=30)),
                ('is_half_day', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
