# Generated by Django 6.0.4 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_holiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancealert',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='approval_section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendancealert',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
