# Generated by Django 6.0.4 on 2026-05-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendancealert_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancealert',
            old_name='status',
            new_name='approval_status',
        ),
        migrations.RemoveField(
            model_name='attendancealert',
            name='approval_section',
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='attendance_status',
            field=models.CharField(default='Absent', max_length=10),
            preserve_default=False,
        ),
    ]
