# Generated by Django 6.0.4 on 2026-05-15 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_section_options_section_is_active'),
        ('attendance', '0009_rename_status_attendancealert_approval_status_and_more'),
        ('students', '0008_student_section'),
        ('teachers', '0004_employee_can_access_academics_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'session', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together={('employee', 'session', 'date')},
        ),
    ]
