# Generated by Django 6.0.4 on 2026-05-27 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_academicsession_options_alter_class_options_and_more'),
        ('attendance', '0010_alter_studentattendance_unique_together_and_more'),
        ('students', '0010_student_religion_student_village'),
        ('teachers', '0005_employee_assigned_class_employee_assigned_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'section', 'student__roll_no', 'student__student_name']},
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', 'employee__name']},
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='viewed_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancealert',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to='teachers.employee'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mobile', 'Mobile'), ('Import', 'Import')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mobile', 'Mobile'), ('GPS', 'GPS')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancealert',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_records', to='students.student'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendance_records', to='teachers.employee'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('date', 'title')},
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['alert_type', 'approval_status'], name='attendance__alert_t_0bb5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancealert',
            index=models.Index(fields=['date'], name='attendance__date_744eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='attendance__date_54d65e_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_eb91f3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['date'], name='attendance__date_12ec13_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['status'], name='attendance__status_938ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['section'], name='attendance__section_4a018a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentattendance',
            index=models.Index(fields=['session', 'date'], name='attendance__session_eb2fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['date'], name='attendance__date_1aa22a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['status'], name='attendance__status_54e06e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherattendance',
            index=models.Index(fields=['session', 'date'], name='attendance__session_d437e2_idx'),
        ),
    ]
