# Generated by Django 6.0.4 on 2026-06-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_studentattendance_options_and_more'),
        ('students', '0013_remove_student_deleted_at_remove_student_is_deleted'),
        ('teachers', '0007_employee_deleted_at_employee_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'student']},
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', '-marked_at']},
        ),
        migrations.RemoveIndex(
            model_name='attendancealert',
            name='attendance__alert_t_0bb5e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancealert',
            name='attendance__date_744eb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='attendance__date_54d65e_idx',
        ),
        migrations.RemoveIndex(
            model_name='holiday',
            name='attendance__is_acti_eb91f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance__date_12ec13_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance__status_938ff8_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance__section_4a018a_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentattendance',
            name='attendance__session_eb2fe3_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacherattendance',
            name='attendance__date_1aa22a_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacherattendance',
            name='attendance__status_54e06e_idx',
        ),
        migrations.RemoveIndex(
            model_name='teacherattendance',
            name='attendance__session_d437e2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='attendancealert',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.employee'),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RemoveField(
            model_name='attendancealert',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='attendancealert',
            name='viewed_by_admin',
        ),
        migrations.RemoveField(
            model_name='attendancealert',
            name='whatsapp_sent',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='marked_at',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='marked_by',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='source',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='source',
        ),
    ]
