# Generated by Django 6.0.4 on 2026-06-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_studentattendance_options_and_more'),
        ('teachers', '0007_employee_deleted_at_employee_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_student_attendance', to='teachers.employee'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Mobile', 'Mobile'), ('Biometric', 'Biometric'), ('Import', 'Import')], default='Manual', max_length=30),
        ),
    ]
