# Generated by Django 6.0.4 on 2026-06-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_studentattendance_marked_by_studentattendance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('GPS', 'GPS'), ('Biometric', 'Biometric'), ('Import', 'Import')], default='Manual', max_length=30),
        ),
    ]
